### ISSUE TITLE
TailwindCSS Intellisense Extension not working

### ISSUE THREAD

**Issue by jerriclynsjohn** [svelte-add/tailwindcss#12]
Loved this, Tailwindcss is set up in under a minute but the intellisense extension doesn't work. Do you think it is because of `.cjs` extension for tailwind config

**Comment by babichjacob** [comment]
The latest versions of the Tailwind CSS IntelliSense extension will support `.cjs` extensions: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/198

**Comment by jerriclynsjohn** [comment]
So what do you think would be the problem here. It just wouldn't work, is it the same for everyone else or if it's working for others did you did something other than the normal to get it working.

**Comment by babichjacob** [comment]
Marking this as "help wanted" so other people can comment.

**Comment by droher** [comment]
I came here to post an issue which might be related -- CSS highlighting doesn't work with just `lang="postcss"`
![image](https://user-images.githubusercontent.com/18269460/111080220-d3b8c680-84d3-11eb-9b4f-1ec4fd92f0f8.png)

But it does work if you add the style attribute as well:
![image](https://user-images.githubusercontent.com/18269460/111080244-f77c0c80-84d3-11eb-9778-88bbd9968d12.png)

Despite it being specified as a default in `svelte.config.cjs`:
```
preprocess: [
		sveltePreprocess({
			defaults: {
				style: "postcss",
			},
			postcss: true
		}),
		]
```

I'm extremely new to all this, so apologies if unrelated/an issue on my end.

**Comment by babichjacob** [comment]
> I came here to post an issue which might be related -- CSS highlighting doesn't work with just `lang="postcss"`
> ![image](https://user-images.githubusercontent.com/18269460/111080220-d3b8c680-84d3-11eb-9b4f-1ec4fd92f0f8.png)
> 
> But it does work if you add the style attribute as well:
> ![image](https://user-images.githubusercontent.com/18269460/111080244-f77c0c80-84d3-11eb-9778-88bbd9968d12.png)
> 
> Despite it being specified as a default in `svelte.config.cjs`:
> 
> ```
> preprocess: [
> 		sveltePreprocess({
> 			defaults: {
> 				style: "postcss",
> 			},
> 			postcss: true
> 		}),
> 		]
> ```
> 
> I'm extremely new to all this, so apologies if unrelated/an issue on my end.

Gonna look into this (eventually), thanks.

**Comment by peterbabic** [comment]
I believe I made it working by symlinking `tailwind.config.cjs` -> `tailwind.config.js` but I am not really sure about other consequences

**Comment by CaptainCodeman** [comment]
I've found I just have to sometimes re-start VS.Code and it starts working - esp. if I've added the libs / config while the editor is open.

**Comment by babichjacob** [comment]
Indeed, for me it just worked to reload.

**Comment by babichjacob** [comment]
Closing this because no one has come back to say they have the same issue. We can reopen it if it's still a problem.

**Comment by bstro** [comment]
I just experienced this issue. It worked after reloading VS Code.
Running 0.5.9 of the extension, and used this package via npx.

```
Version: 1.55.0-insider (Universal)
Commit: d06d2f1d6245ce00b1c36a9cd81a9087d225173e
Date: 2021-03-26T13:57:45.993Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```
