### ISSUE TITLE
Info / Error : Must use import to load ES Module

### ISSUE THREAD

**Issue by fmgono** [svelte-add/tailwindcss#16]
when i run command `npx svelte-add tailwindcss`, the terminal return this :
Must use import to load ES Module: /home/fathan/.npm/_npx/26974/lib/node_modules/svelte-add/index.js

**Comment by fmgono** [comment]
already solved with command `npx apply svelte-add/tailwindcss` form [Svelte-add NPM](https://www.npmjs.com/package/svelte-add)

**Comment by babichjacob** [comment]
What version of Mode were you on?
