### ISSUE TITLE
tailwind without postcss?

### ISSUE THREAD

**Issue by tbillington** [svelte-add/tailwindcss#24]
Just curious, is it possible to get tailwind without postcss? If possible I'd rather not add more build steps to a project. Previously I'd just generate the tailwind css file and include that without needing to have postcss run in the project, but it looks like the jit requires postcss?

**Comment by babichjacob** [comment]
Tailwind is a PostCSS plugin. It's always required. (Even when you run `tailwindcss build` or don't have a PostCSS config file, one is used without showing you).

Look into [Windi CSS](https://windicss.org/) for a Tailwind-compatible API without PostCSS. We even have the rudimentary [`svelte-add/postcss`](https://github.com/svelte-add/windicss).

**Comment by tbillington** [comment]
Oh I didn't realise it was a postcss plugin, thank you :)
