### ISSUE TITLE
The dev server works fine but the production build (adapter-static) doesn't have any styles

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/tailwindcss#31]
Making this issue to help @seanaye
https://github.com/seanaye/geog483-final/tree/master/client

**Comment by seanaye** [comment]
If it helps, the css files are correctly bundled in the output directory. If I manually add `<link rel="...` to the index.html then the page renders as expected. 

It appears that the adapter-static is just never importing the styles anywhere in the bundled output

**Comment by fkoeppling** [comment]
+1

**Comment by babichjacob** [comment]
I don't know what more to say than that I tried it earlier today on a new project and it worked as expected.

**Comment by babichjacob** [comment]
Oh oops, I forgot to try your specific repo. That's gonna have to wait a while because of school; I'm sorry.

**Comment by seanaye** [comment]
haha no worries, I'm in school right now too, I know the struggle

**Comment by babichjacob** [comment]
Was this fixed this morning? https://github.com/sveltejs/kit/issues/924

Update your dependencies and try again, because it worked for me when I tested now (with that update of course).

**Comment by seanaye** [comment]
Yes this has resolved the problem, thanks for looking into it
