### ISSUE TITLE
how to make Tailwind CSS Intellisense work in vscode

### ISSUE THREAD

**Issue by opensas** [svelte-add/tailwindcss#35]
I have Tailwind CSS Intellisense installed but it doesn't seem to work

I tried both with a vite and a sveltekit project, same thing happens with both

Am I missing something?

**Comment by babichjacob** [comment]
Related issue: https://github.com/svelte-add/tailwindcss/issues/12

You have to reload VS Code after running the adder command.

**Comment by babichjacob** [comment]
Does that solve it?

**Comment by teds31** [comment]
There might be some conflicts with your settings as well, which I would take a look at. But typically it runs well out of the box. Only issue is that you may have to delete the last letter of a utility in order for the options/recommendations to pop up when you are adding another utility class to an element

**Comment by opensas** [comment]
> Does that solve it?

Yes, that solved the issue! thanks
