### ISSUE TITLE
Add Tailwindcss JIT, am I doing something wrong ?

### ISSUE THREAD

**Issue by dok42** [svelte-add/tailwindcss#41]
Hello
I've started a new project with
`npm init svelte@next`
then
`npx svelte-add tailwindcss --jit` not `npx svelte-add tailwindcss # --jit`
Is this correct ? then I did 
`npm install`

Is anything else I need to change? config files ?
In some tutorial I read to change extension to `svelte.config.js` file, changing it to `svelte.config.cjs`

Now, I'm not sure how this Jit compiler works.
I kind of expect something similar to how https://play.tailwindcss.com/ works, where whenever there is a code change the preview update instantly. 

In VSCode instead, actually I've to save the file to update the preview (localhost:3000).

Am I doing something wrong or it's just normal ? 
Thank you

**Comment by sveltemaster** [comment]
i'm not sure why this broke exactly but in the mean time I thiiink you can just manually add a file
called app.postcss with contents of
@tailwind base;
@tailwind components;
@tailwind utilities;
and then in __layout.svelte put something like
<script>
	import "../app.postcss";
</script>

<slot />
<img width="1440" alt="Screen Shot 2021-05-07 at 6 26 07 PM" src="https://user-images.githubusercontent.com/56200325/117521252-b2b7a380-af61-11eb-9b43-40508ff0765b.png">

**Comment by dok42** [comment]
Hi, and thank you :) 
Those files were already there, I mean, the `app.postcss`. Here the `__layout.svelte` is `$layout.svelte`
![tailwind](https://user-images.githubusercontent.com/25151676/117533495-792c7a00-afed-11eb-951d-da00922e06bd.jpg)

Also, here is my package.json and postcss.config.cjs.
![package_e_config](https://user-images.githubusercontent.com/25151676/117533645-2a331480-afee-11eb-98f5-ce676204ab49.jpg)

I think it should works, It's a fresh install and I followed the install instructions step by step, it should works but somehow it... doesen't ???

**Comment by babichjacob** [comment]
> Expected behavior: TEST change to blu (like in play.tailwindcss.com)
> Actual behavior: **I need to save the file** for the TEST to change to blu. Is this how it should be ?

Yes. Change your VS Code settings to automatically save files when you write.

**Comment by dok42** [comment]
Well.. where this "Auto save" setting came from? 😄 
Thank you very much :), Sorry I didn't now about this setting, seems like it's working now.
Closed for me.

**Comment by babichjacob** [comment]
> Well.. where this "Auto save" setting came from? 😄
> Thank you very much :), Sorry I didn't now about this setting, seems like it's working now.
> Closed for me.

Check this out. These are what my settings are like:

![image](https://user-images.githubusercontent.com/22732095/117560476-2e961680-b05c-11eb-803a-47075b3704bf.png)
