### ISSUE TITLE
Cannot find module path/posix while running npx svelte-add tailwindcss

### ISSUE THREAD

**Issue by chenchunaidu** [svelte-add/tailwindcss#44]
I am getting this error while running npx svelte-add tailwindcss
```
Cannot find module 'path/posix'
Require stack:
/lib/node_modules/svelte-add/cli.cjs
```

**Comment by babichjacob** [comment]
Thanks for the report! This is a mistake I'll need to fix later today (when I'm home). 

If you were curious, this came from an IDE auto import I failed to notice was from the wrong library.

**Comment by babichjacob** [comment]
Fixed by https://github.com/svelte-add/svelte-add/commit/249d5f95456adc3902fe234a32f8852d1d36159d
