### ISSUE TITLE
It's not working with latest svelte kit , date : 30-01-2021

### ISSUE THREAD

**Issue by mishrasatyam** [svelte-add/tailwindcss#5]

**Comment by babichjacob** [comment]
Looks like it just worked for me on a new project. Can you provide more information?

**Comment by mishrasatyam** [comment]
I followed the instructions but styles are not being applied.
This is the code [github link](https://github.com/mishrasatyam/svelte-tailwind-test)
![Screenshot (9)](https://user-images.githubusercontent.com/31180325/106349311-10997700-62f3-11eb-8edb-8bc631d62e6c.png)

**Comment by babichjacob** [comment]
I'm really sorry this is happening. Please put `tailwindcss(),` after `autoprefixer,` in the `plugins` array in the `postcss.config.js` file and it should work.

**Comment by mishrasatyam** [comment]
It's working now. Thanks for quick response!!

**Comment by babichjacob** [comment]
Closing to keep all discussion / investigation in #4

**Comment by Evertt** [comment]
It also doesn't work for me. After following the instructions in the README I ended up with this in `postcss.config.cjs`:

```
module.exports = {
	plugins: [
		// Some plugins, like postcss-nested, need to run before Tailwind
		
		tailwindcss("./tailwind.config.cjs"),
		
		// But others, like autoprefixer, need to run after

		autoprefixer,
		
		!dev && cssnano({
			preset: "default",
		}),
	],
};
```

But I had the same problem as OP, that the styles from within `Counter.svelte` were not being applied. @babichjacob I tried your suggestion:

> I'm really sorry this is happening. Please put `tailwindcss()`, after `autoprefixer`, in the `plugins` array in the `postcss.config.js` file and it should work.

Well I don't have a `postcss.config.js` file, but I do have a `postcss.config.cjs` file, so I assume you meant the latter one. Anyway, I tried that, but it made no difference.

**Comment by babichjacob** [comment]
> It also doesn't work for me. After following the instructions in the README I ended up with this in `postcss.config.cjs`:
> 
> ```
> module.exports = {
> 	plugins: [
> 		// Some plugins, like postcss-nested, need to run before Tailwind
> 		
> 		tailwindcss("./tailwind.config.cjs"),
> 		
> 		// But others, like autoprefixer, need to run after
> 
> 		autoprefixer,
> 		
> 		!dev && cssnano({
> 			preset: "default",
> 		}),
> 	],
> };
> ```
> 
> But I had the same problem as OP, that the styles from within `Counter.svelte` were not being applied. @babichjacob I tried your suggestion:
> 
> > I'm really sorry this is happening. Please put `tailwindcss()`, after `autoprefixer`, in the `plugins` array in the `postcss.config.js` file and it should work.
> 
> Well I don't have a `postcss.config.js` file, but I do have a `postcss.config.cjs` file, so I assume you meant the latter one. Anyway, I tried that, but it made no difference.

@Evertt This is something different. I just made #7 for this.
