### ISSUE TITLE
Failing run of `npx svelte-add tailwindcss --jit`

### ISSUE THREAD

**Issue by etano** [svelte-add/tailwindcss#51]
Fresh install of sveltekit skeleton project gave this:

```
ethan@siv:~/src/serot/site$ npx svelte-add tailwindcss --jit
➕ Svelte Add
The project directory you're giving to this command cannot be guaranteed to be fresh. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

tailwindcss
/Users/ethan/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/cli.cjs:232
		reject(new Error(body));
		       ^

Error: npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information

    at Socket.<anonymous> (/Users/ethan/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/cli.cjs:232:10)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
 ```

**Comment by AndyCormack** [comment]
This seems to be related to npm v7 and its choice to remove the ignore-existing flag and thus needs fixing in the svelte-add repo itself: https://github.com/svelte-add/svelte-add/blob/4b663d6cd89cf1c6fdb07e81403f41c9003a0e9a/projects/svelte-add/index.js#L275

In the mean time you can downgrade your npm version using nvm or doing a `npm i -g npm@6`

**Comment by jthegedus** [comment]
`mode: 'jit'` in `tailwind.config.cjs` enables JIT in Tailwind `v2.1` and above. It is part of the core lib now.

**Comment by babichjacob** [comment]
This was fixed by https://github.com/svelte-add/svelte-add/commit/7daf56ecc60e062f5915d7d8e5e15ae9ce6e81d5. You will probably get a different error than this that I need to solve, though, because of the current state of `svelte-add`.
