### ISSUE TITLE
Error when running init command

### ISSUE THREAD

**Issue by rohanharikr** [svelte-add/tailwindcss#54]
When running `npx svelte-add tailwindcss --jit` on a Sveltekit project, this error is thrown:
<img width="292" alt="Screenshot 2021-06-02 at 11 50 01 PM" src="https://user-images.githubusercontent.com/12775813/120532550-62ffb700-c3fd-11eb-92df-9ba95834b6b8.png">

**Comment by rohanharikr** [comment]
A thing to note is that it works if I downgrade the npm version `npm i -g npm@6`

**Comment by babichjacob** [comment]
A lot has changed since this issue was created, so it may have been solved by now. Please try again and feel free to open a new issue (or find an existing one) at https://github.com/svelte-add/svelte-add/issues if you encounter a problem.
