### ISSUE TITLE
cjs extension for SvelteKit

### ISSUE THREAD

**Issue by benmccann** [svelte-add/tailwindcss#6]
I had to change

https://github.com/svelte-add/tailwindcss/blob/16cfb53bc3b022edcc56d36980a2ae06971506cb/preset.ts#L10

To be:

		tailwindcss({ config: './tailwind.config.cjs' }),

**Comment by babichjacob** [comment]
This may be solved by 500cb8f9e32fcb499fede2ba473cd5f4e8107a5a, but I haven't tested it yet.
