### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by GrygrFlzr** [svelte-add/tailwindcss#8]
## Confirming base tailwind works
1. Setup:
```sh
# selected Y for typescript, CSS for styles
npm init svelte@next

# said yes to update node dependencies
npx apply svelte-add/postcss

# said yes to update node dependencies
npx apply svelte-add/tailwindcss

npm install
npm update
```
2. I also manually added tailwind to the `postcss.config.cjs` since I'm on Windows with CRLF endings and #4 is in effect:
```js
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");

const mode = process.env.NODE_ENV;
const dev = mode === "development";

module.exports = {
  plugins: [
    tailwindcss,
    autoprefixer,

    !dev &&
      cssnano({
        preset: "default",
      }),
  ],
};
```
3. Use the custom snowpack config as per #7.
4. Confirm that sort-of-out-of-the-box experience works.

## Testing class-based dark mode
1. Enable class dark mode in `tailwind.config.cjs` and comment out all purging, to rule it out as a potential variable:
```
module.exports = {
  darkMode: "class",
  //   purge: {
  //     ...
  //    },
  // ...
};
```
2. Update `index.svelte` to apply the `dark` class:
```html
<main class="dark">
```
3. Update `Counter.svelte` to apply a background on dark mode:
```svelte
<button on:click={increment} class="dark:bg-gray-900">
```
4. `npm run dev` to observe that the classes are on the element, but no change has occured, and no dark-mode CSS rules are being applied/overridden (you can use the inspector to check this).
5. Undo step 3 and change the button style with `@apply` instead:
```css
  button {
    /* ... */
    @apply dark:bg-gray-900;
  }
```
An error will appear:
```
Build Error: @snowpack/plugin-svelte
CssSyntaxError: C:\Users\GrygrFlzr\Documents\projects\tw-test\src\components\Counter.svelte:15:12: The `dark:bg-gray-900` class does not exist, but `2xl:bg-gray-900` does. If you're sure that `dark:bg-gray-900` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  13 |     @apply w-48;
  14 |     font-variant-numeric: tabular-nums;
> 15 |     @apply dark:bg-gray-900;
     |            ^
  16 |   }
  17 | 
```

## Testing media-based dark mode
Repeat the above section, except with `darkMode: "media"`, and setting the browser preference to dark mode.

## Other attempts
I've also attempted both the class and media modes with explicitly adding support for the dark `backgroundColor` variant, to no avail:
```js
// tailwind.config.cjs
module.exports = {
  // ...
  variants: {
    extend: {
      backgroundColor: ['dark']
    }
  }
}
```

**Comment by babichjacob** [comment]
Hi, I'm really sorry this isn't working 😦. Thank you for the detailed issue!

> ## Confirming base tailwind works
> 
> 1. Setup:
> 
> 
> ```sh
> # selected Y for typescript, CSS for styles
> npm init svelte@next
> 
> # said yes to update node dependencies
> npx apply svelte-add/postcss
> 
> # said yes to update node dependencies
> npx apply svelte-add/tailwindcss
> 
> npm install
> npm update

Good
> 1. I also manually added tailwind to the `postcss.config.cjs` since I'm on Windows with CRLF endings and #4 is in effect:
> 
> 
> ```js
>  ...
> ```
Oh no! I haven't updated that yet to have `tailwindcss("./tailwind.config.cjs"),` instead of just `tailwindcss`. I'm sorry!
Your Tailwind config file isn't being used.

Please also confirm that `svelte.config.cjs` has
```js
const sveltePreprocess = require("svelte-preprocess");
module.exports = {
	preprocess: [
		sveltePreprocess({
			defaults: {
				style: "postcss",
			},
			postcss: true,
		}),
	],
	kit: {
		// By default, `npm run build` will create a standard Node app.
		// You can create optimized builds for different platforms by
		// specifying a different adapter
		adapter: '@sveltejs/adapter-static',

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};
```
because that *may* also happen for the same reason.

> 1. Use the custom snowpack config as per #7.
> 
> 2. Confirm that sort-of-out-of-the-box experience works.
> 
Good 

(going out of order here)
> ## Testing media-based dark mode
> 1. Enable media dark mode in `tailwind.config.cjs` and comment out all purging, to rule it out as a potential variable:
> ```js
> module.exports = {
>   darkMode: "media",
>   //   purge: {
>   //     ...
>   //    },
>   // ...
> };
> ```
> set the browser preference to dark mode.
> 1. Update `Counter.svelte` to apply a background on dark mode:
> 
> 
> ```svelte
> <button on:click={increment} class="dark:bg-gray-900">
> ```
Just worked for me. (Even with purge enabled and running a `build` + `adapt` step to see it survived).

> ## Testing class-based dark mode
> 1. Enable class dark mode in `tailwind.config.cjs` and comment out all purging, to rule it out as a potential variable:
> ```js
> module.exports = {
>   darkMode: "class",
>   //   purge: {
>   //     ...
>   //    },
>   // ...
> };
> ```
> 2. Update `index.svelte` to apply the `dark` class:
> 
> 
> ```html
> <main class="dark">
> ```
> 
> 1. `npm run dev` to observe that the classes are on the element, but no change has occured, and no dark-mode CSS rules are being applied/overridden (you can use the inspector to check this).

Nope, this also worked.

> 2. Undo step 3 and change the button style with `@apply` instead:
> 
> 
> ```css
>   button {
>     /* ... */
>     @apply dark:bg-gray-900;
>   }
> ```
> 
> An error will appear:
> 
> ```
> Build Error: @snowpack/plugin-svelte
> CssSyntaxError: C:\Users\GrygrFlzr\Documents\projects\tw-test\src\components\Counter.svelte:15:12: The `dark:bg-gray-900` class does not exist, but `2xl:bg-gray-900` does. If you're sure that `dark:bg-gray-900` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
> 
>   13 |     @apply w-48;
>   14 |     font-variant-numeric: tabular-nums;
> > 15 |     @apply dark:bg-gray-900;
>      |            ^
>   16 |   }
>   17 | 
> ```
> 

Two issues:
1. Previously mentioned that the Tailwind config file isn't being used, so dark mode isn't available by default
2. Don't `@apply` classes that depend on classes outside the current component (i.e. class-based `dark`) in a `style` block unless you mark it as `global`:

```html
<style lang="postcss" global>
    button {
        @apply dark:text-green-100 dark:bg-green-800;
    }
</style>
```

This is going to break scoping / encapsulation, so to undo that, mark that style as `local`:

```html
<style lang="postcss" global>
    :local(button) {
        @apply dark:text-green-100 dark:bg-green-800;
    }
</style>
```

> ## Other attempts
> 
> I've also attempted both the class and media modes with explicitly adding support for the dark `backgroundColor` variant, to no avail:
> 
> ```js
> // tailwind.config.cjs
> module.exports = {
>   // ...
>   variants: {
>     extend: {
>       backgroundColor: ['dark']
>     }
>   }
> }
> ```
Lastly, this didn't work because (again) the Tailwind config file wasn't being used.

**Comment by GrygrFlzr** [comment]
> Oh no! I haven't updated that yet to have `tailwindcss("./tailwind.config.cjs")`, instead of just `tailwindcss`. I'm sorry!
> Your Tailwind config file isn't being used.

Ah, yep, that fixed it. Thanks for the quick response! Should I close the issue since the core of this is #4?

**Comment by babichjacob** [comment]
Yes, thank you.
